version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_nubepersonal
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superseguro123
      POSTGRES_DB: nubepersonal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
